name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check CHANGELOG.md file for changes
        run: |
          git diff --name-only HEAD~1 HEAD | grep "CHANGELOG.md"
          if [ $? -eq 0 ]; then
            echo "CHANGELOG.md file was modified in this PR."
          else
            echo "The CHANGELOG.md file needs to be modified in this PR before doing Merge."
            exit 1
          fi  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: go build -v ./...
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Test
      run: go test -v ./...

