name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check CHANGELOG.md file for changes
        run: |
          git branch -a
          if [ -z "$(git diff --name-only remotes/origin/HEAD -- README.md)" ]; then
            echo "The CHANGELOG.md file needs to be modified in this PR before doing Merge."
            exit 1
          fi  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build
      run: go build -v ./...
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Test
      run: go test -v ./...

